#include "Python.h"

#include "pycore_interpframe_structs.h"
#include "pycore_stackref.h"

#include <stddef.h>
#include <stdio.h>

int
main(void)
{
    puts("/* Generated by generate_bpf_stack_offsets.c; do not edit. */");
    puts("#ifndef PY_BPF_STACK_OFFSETS_H");
    puts("#define PY_BPF_STACK_OFFSETS_H");
    printf("#define PY_BPF_TSTATE_CURRENT_FRAME %zu\n", offsetof(PyThreadState, current_frame));
    printf("#define PY_BPF_TSTATE_BASE_FRAME %zu\n", offsetof(PyThreadState, base_frame));
    printf("#define PY_BPF_FRAME_PREVIOUS %zu\n", offsetof(_PyInterpreterFrame, previous));
    printf("#define PY_BPF_FRAME_EXECUTABLE %zu\n", offsetof(_PyInterpreterFrame, f_executable));
    printf("#define PY_BPF_CODE_FILENAME %zu\n", offsetof(PyCodeObject, co_filename));
    printf("#define PY_BPF_CODE_QUALNAME %zu\n", offsetof(PyCodeObject, co_qualname));
    printf("#define PY_BPF_UNICODE_LENGTH %zu\n", offsetof(PyASCIIObject, length));
    printf("#define PY_BPF_UNICODE_STATE %zu\n", offsetof(PyASCIIObject, state));
    printf("#define PY_BPF_UNICODE_ASCII_DATA %zu\n", sizeof(PyASCIIObject));
    printf("#define PY_BPF_STACKREF_REFCNT_MASK %u\n", Py_TAG_REFCNT);
    puts("#define PY_BPF_UNICODE_STATE_ASCII_MASK (1U << 6)");
    puts("#endif");
    return 0;
}
